# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QGraphicsScene, QGraphicsView
from PyQt5.QtCore import Qt, pyqtSlot


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        self.img = QPixmap('output.jpg')
        self.scenes = QGraphicsScene()
        self.scenes.addPixmap(self.img)
        self.graphicsView = QtWidgets.QGraphicsView(self.scenes, Form)
        self.graphicsView.setGeometry(QtCore.QRect(200, 10, 600, 420))
        self.graphicsView.setObjectName("graphicsView")
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 460, 93, 28))
        self.pushButton.setText('-')
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 460, 93, 28))
        self.pushButton_2.setText('+')
        self.pushButton.clicked.connect(self.zoom_out)
        self.pushButton_2.clicked.connect(self.zoom_in)

    def zoom_in(self):
        factor = 1.5
        scale_tr = QtGui.QTransform()
        scale_tr.scale(factor, factor)

        tr = self.graphicsView.transform() * scale_tr
        self.graphicsView.setTransform(tr)

    def zoom_out(self):
        factor = 1.5
        scale_tr = QtGui.QTransform()
        scale_tr.scale(factor, factor)

        scale_inverted, invertible = scale_tr.inverted()

        if invertible:
            tr = self.graphicsView.transform() * scale_inverted
            self.graphicsView.setTransform(tr)

    def toggleFullscreen(self):
        if self.isFullScreen():
            self.showNormal()
        else:
            self.showFullScreen()

    def keyPressEvent(self, Form):
        if Form.key() == QtCore.Qt.Key_F11 or Form.key() == QtCore.Qt.Key_F:
            self.toggleFullscreen()

    def wheelEvent(self, Form):
        if Form.modifiers() == Qt.ControlModifier:
            delta = Form.angleDelta().y()
            if delta > 0:
                self.zoom_in()

            elif delta < 0:
                self.zoom_out()

        else:
            return super().wheelEvent(Form)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
